config/routes.rb
Rails.application.routes.draw do
  devise_for :experts
  devise_for :users

  root 'wines#search'

  resources :wines, only: %i[search show] do
    resources :reviews, only: %i[show create update]
    get   'reviews', to: 'reviews#show', param: :wine_id, as: 'show_review'
    post  'reviews', to: 'reviews#create', on: :member, as: 'create_review'
    patch 'reviews', to: 'reviews#update', on: :member, as: 'update_review'
  end

  resources :searches, only: :index

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expert.rb
class Expert < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :reviews
  has_many :searches

  has_many :notifications, as: :recipient, dependent: :destroy
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :wine
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :wine
  belongs_to :expert

  after_create :recalculate_average_rating_job

  private

  def recalculate_average_rating_job
    RecalculateAverageRatingJob.perform(wine_id)
  end
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :expert, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :searches

  has_many :notifications, as: :recipient, dependent: :destroy
end

app/models/wine.rb
# frozen_string_literal: true

# Wine Model
class Wine < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  extend Pagy::ElasticsearchRails

  belongs_to :recipient, class_name: 'User'
  belongs_to :recipient, class_name: 'Expert'

  after_create_commit :wine_matches_previous_search

  has_many :reviews, dependent: :destroy
  has_many :prices, dependent: :destroy

  index_name "wines-#{Rails.env}"

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :name, type: 'text'
      indexes :properties, type: 'text'
      indexes :price, type: 'float'
      indexes :marketplace, type: 'text'
      indexes :note, type: 'float'
      indexes :wine_type, type: 'text'
    end
  end

  def as_indexed_json(_ = {})
    as_json(only: %i[name properties price marketplace note wine_type])
  end

  def average_rating
    if reviews.count.positive?
      reviews.average(:rating).to_f
    else
      0.0
    end
  end

  # This method calculates the average rating of the wine
  def recalculate_average_rating
    self.note = average_rating
    save
  end

  def wine_matches_previous_search
    wine = self
    search_results = Search.where('query LIKE ?', "%#{wine.id}%")
    user_ids = search_results.pluck(:user_id)
    expert_ids = search_results.pluck(:expert_id)

    user_ids.each do |_user_id|
      # Notify the user
      NewMessageNotification.with(message: self).deliver_later(recipient)
    end

    expert_ids.each do |_expert_id|
      # Notify the expert
      NewMessageNotification.with(message: self).deliver_later(recipient)
    end
  end
end

app/controllers/application_controller.rb
# Application controller
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_expert!
  before_action :set_wine, only: %i[show create update]

  def show
    @reviews = @wine.reviews
    @review = @wine.reviews.find_by(expert_id: current_expert.id) || @wine.reviews.build
  end

  def create
    @review = @wine.reviews.find_or_initialize_by(
      expert_id: current_expert.id
    )
    @review.assign_attributes(review_params)

    if @review.save
      redirect_to wine_path(@wine)
    else
      render :show
    end
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to wine_path(@wine)
    else
      render :show
    end
  end

  private

  def set_wine
    @wine = Wine.find(params[:wine_id])
  end

  def review_params
    params.require(:review).permit(:message, :rating)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  include Pagy::Backend

  def index
    if user_signed_in?
      @pagy, @searches = pagy(current_user.searches.limit(5))
    elsif expert_signed_in?
      @pagy, @searches = pagy(current_expert.searches.limit(5))
    else
      redirect_to root_path
    end
  end
end

app/controllers/wines_controller.rb
# frozen_string_literal: true

# Wines controller
class WinesController < ApplicationController
  include Pagy::Backend
  include WineHelper

  before_action :set_wine, only: %i[show]

  def index
    @pagy, @wines = pagy(Wine.limit(6))
  end

  def show
    per_page = 3
    @wine = Wine.includes(:reviews, :prices).find(params[:id])
    all_reviews = @wine.reviews.order(Arel.sql("CASE WHEN reviews.expert_id = #{current_expert&.id.to_i} THEN 0 ELSE 1 END, reviews.updated_at DESC"))
    @prices = @wine.prices.order(:date)

    @pagy, @paginated_reviews = pagy(all_reviews, items: per_page)
  end

  def search
    @pagy, @wines = search_wines
    redirect_to_last_page if @pagy.pages < params[:page].to_i
  end

  private

  def set_wine
    @wine = Wine.find(params[:id])
  end
end

app/helpers/application_helper.rb
# Application helper
module ApplicationHelper
  require 'time'

  def convert_time(date_string)
    date = Time.parse(date_string)
    date.strftime('%d/%m/%Y à %Hh%M')
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/wine_helper.rb
module WineHelper
  def search_wines
    if params[:q].present?
      save_search
      search_response = Wine.__elasticsearch__.search(
        query: {
          multi_match: {
            query: params[:q],
            fields: %w[name properties marketplace]
          },
        },
        sort: [{ note: 'desc' }]
      )
      searches = search_response.records
      pagy(searches, items: 6)
    else
      pagy(sorted_wines, items: 6)
    end
  end

  def save_search
    return unless user_signed_in? || expert_signed_in?

    search = Search.find_or_create_by!(query: params[:q]) do |s|
      s.expert_id = current_expert&.id
      s.user_id = current_user&.id
    end

    search.touch
  end

  def redirect_to_last_page
    redirect_to action: 'search', q: params[:q]
  end

  def sorted_wines
    Wine.order(note: :desc)
  end
end

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>TestTechniqueIlek</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://cdn.tailwindcss.com"></script>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  <%= javascript_pack_tag 'application' %>

</head>

<body>
<header class="bg-black text-white w-full">
  <nav class="flex justify-between items-center w-[92%]  mx-auto">
    <a href="/" class="flex justify-between items-center bg-white text-black rounded-full m-2 hover:bg-red-800 hover:text-white transition">
      <img
        class="p-2 w-16 mr-1"
        src="https://res.cloudinary.com/dttd773dq/image/upload/v1697274692/ilek-assets/images/wine-bottle_uatwvb.png"
        alt="logo"
        />
      <i class="text-3xl font-bold mr-3">Wine search</i>
    </a>
    <ul class="hidden md:flex px-4 mx-auto font-semibold font-heading space-x-12">
      <li><%= link_to 'Home', root_path, class: 'hover:text-gray-200' %></li>
      <% if user_signed_in? or expert_signed_in? %>
        <li><%= link_to 'My searches', searches_path, class: 'hover:text-gray-200' %></li>
      <% end %>
    </ul>
    <div class="ml-auto mr-3">
      <%= react_component("Notification") %>
    </div>
    <% if user_signed_in? %>
      <div class="mr-3 text-center">
        <h5 class="text-white"><%= current_user.email %></h5>
      </div>
      <div>
        <%= button_to 'Sign out', destroy_user_session_path, class: 'bg-white text-black px-5 py-2 rounded-full hover:opacity-75', method: :delete %>
      </div>
    <% elsif expert_signed_in? %>
      <div class="mr-3 text-center">
        <h5 class="text-white"><%= current_expert.email %> - expert</h5>
      </div>
      <div>
        <%= button_to 'Sign out', destroy_expert_session_path, class: 'bg-white text-black px-5 py-2 rounded-full hover:opacity-75', method: :delete %>
      </div>
    <% else %>
      <div class="flex items-center gap-6">
        <%= link_to 'Sign in', user_session_path, class: 'hover:text-gray-500' %>
        <%= link_to 'Register', new_user_registration_path, class: 'bg-[#a20848] hover:opacity-75 focus:opacity-75 text-white px-5 py-2 rounded-full', method: :get %>
        <%= link_to "I'm an expert", expert_session_path, class: 'bg-green-500 text-white px-5 py-2 rounded-full hover:bg-green-700', method: :get %>
      </div>
    <% end %>
  </nav>
</header>

<main>
  <%= yield %>
</main>
</body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReactOnRailsWithShakapacker</title>
  <%= csrf_meta_tags %>
  <%= javascript_pack_tag 'hello-world-bundle' %>
  <%= stylesheet_pack_tag 'hello-world-bundle' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/reviews/show.html.erb
<div class="container mx-auto p-6">
  <div class="relative p-6 flex w-full flex-row text-gray-700">
    <div class="relative m-0 flex justify-center items-center shrink-0 overflow-hidden rounded-xl rounded-r-none bg-white bg-clip-border text-gray-700">
      <img
        src="https://res.cloudinary.com/dttd773dq/image/upload/v1697274692/ilek-assets/images/wine-bottle_uatwvb.png"
        alt="image"
        class="h-48 w-48 object-cover"
        />
    </div>
    <div class="flex items-center">
      <div>
        <h4 class="text-3xl font-bold mb-4 uppercase leading-relaxed tracking-normal text-[#a20848] antialiased">
          <%= @wine.name %>
        </h4>
        <p class="mb-8 block font-sans text-gray-500 font-normal leading-relaxed antialiased">
          <%= @wine.properties %>
        </p>
      </div>
    </div>
  </div>
  <div class="flex justify-center max-w-3xl mb-6">
    <%= form_with(model: [@wine, @review], local: true) do |form| %>
      <div class="mb-4">
        <%= form.label :message, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.text_area :message, class: "shadow appearance-none border rounded w-full py-6 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", value: @review.message || '' %>
      </div>

      <div class="mb-6">
        <%= form.label :rating, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.number_field :rating, in: 1..5, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", value: @review.rating || 5 %>
      </div>

      <div class="flex items-center justify-between">
        <%= form.submit "Submit", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>
  </div>
  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-4 gap-y-6">
    <% @wine.reviews.each do |review| %>
      <% if review.id != @review.id %>
        <div class="bg-white max-w-sm rounded-2xl flex justify-between flex-col px-10 py-2 shadow-lg hover:shadow-2xl transition duration-500">
          <div class="mt-4 text-md text-gray-600">
            <p><%= review.message %></p>
          </div>
          <div class="mt-auto flex justify-between space-x-4 py-6">
            <div class="text-sm font-semibold">
              <%= review.expert.name %>
              <p class="font-normal text-gray-500"> <%= time_ago_in_words(review.updated_at) %></p>
            </div>
            <div class="flex">
              <% review.rating.times do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-yellow-400" viewBox="0 0 20 20" fill="currentColor">
                  <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"/>
                </svg>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/searches/index.html.erb
<div class="container mx-auto p-6">
  <h1 class="mb-6">Searches</h1>
  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-4 gap-y-6">
    <% @searches.each do |search| %>
      <a href="<%= root_path(q: search.query) %>">
        <div class="bg-white max-w-sm rounded-2xl flex justify-between flex-col px-10 py-2 shadow-lg hover:shadow-2xl transition duration-500">
          <div class="mt-4 text-md text-gray-600">
            <h4>You searched <%= search.query %></h4>
          </div>
          <div class="mt-auto flex justify-between space-x-4 py-6">
            <div class="text-sm font-semibold">
              <p class="font-normal text-gray-500"><%= DateTime.parse(search.updated_at.to_s).strftime('%Y-%m-%d at %H:%M') %></p>
            </div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
  <div class="flex items-center justify-center mt-6">
    <% if @pagy.pages > 1 %>
      <%= pagy_nav(@pagy, link_extra: 'class="border rounded-md px-3 py-1 text-blue-500 mx-1"', link_inactive_extra: 'class="border rounded-md px-3 py-1 text-gray-500 mx-1"').html_safe %>
    <% end %>
  </div>
</div>

app/views/wines/index.html.erb
<div class="bg-white">
  <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
    <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
      <% @wines.each do |wine| %>
        <div class="group relative">
          <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-md bg-gray-200 lg:aspect-none group-hover:opacity-75 lg:h-80">
            <img height="48" src="wine.webp" alt="" class="h-full w-full object-cover object-center lg:h-full lg:w-full">
          </div>
          <div class="mt-4 flex justify-between">
            <div>
              <h3 class="text-sm text-gray-700">
                <a href="#">
                  <span aria-hidden="true" class="absolute inset-0"></span>
                  <%= wine.name %>
                </a>
              </h3>
              <p class="mt-1 text-sm text-gray-500"><%= wine.price.round(2) %>€</p>
            </div>
            <p class="text-sm font-medium text-gray-900"><%= wine.properties %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/wines/new.html.erb
<section class="flex flex-col md:flex-row items-center">

  <div class="bg-[#a20848] hidden lg:block w-full md:w-1/2 xl:w-1/3 h-screen">
    <img
      src="https://res.cloudinary.com/dttd773dq/image/upload/v1697814592/ilek-assets/images/logo_dnngnn.jpg"
      alt=""
      class="w-full h-full object-cover"
      />
  </div>

  <div class="bg-white w-full md:max-w-md lg:max-w-full md:mx-auto md:mx-0 md:w-1/2 xl:w-1/3 h-screen px-6 lg:px-16 xl:px-12
        flex items-center justify-center">

    <div class="w-full h-100">


      <h1 class="text-xl md:text-2xl font-bold leading-tight mt-12 mb-12">Create a wine</h1>

      <%= form_for(resource, as: resource_name, url: session_path(resource_name), class: 'mt-6') do |f| %>

        <div>
          <%= f.label :name, class: 'block text-gray-700' %>
          <%= f.email_field :name, autocomplete: "name", class: 'w-full px-4 py-3 rounded-lg mt-2 border focus:border-blue-500 focus:bg-white focus:outline-none' %>
        </div>

        <%= f.submit "Log in", class: 'w-full block bg-[#a20848] hover:opacity-75 focus:opacity-75 cursor-pointer text-white font-semibold rounded-lg
              px-4 py-3 mt-6' %>
      <% end %>

      <hr class="my-6 border-gray-300 w-full">

      <%= render "devise/shared/links" %>

    </div>
  </div>

</section>

app/views/wines/search.html.erb
<div class="min-w-screen min-h-screen bg-gray-200 px-5 py-5">
  <div class="w-full mx-auto rounded-xl bg-gray-100 shadow-lg p-10 text-gray-800 relative overflow-hidden resize-x min-w-80 max-w-3xl lg:max-w-7xl">
    <!-- Search Bar -->
    <form class="relative mt-1">
      <label for="search"></label>
      <input type="search" id="search" name="q" class="w-full pl-3 pr-10 py-5 border-2 border-gray-200 rounded-xl hover:border-gray-300 focus:outline-none focus:border-blue-500 transition-colors" placeholder="Search a wine..." value="<%= params[:q] %>">
      <button class="block w-7 h-7 text-center text-xl leading-0 absolute top-2 right-2 text-gray-400 focus:outline-none hover:text-gray-900 transition-colors">
        <i class="mdi mdi-magnify"></i>
      </button>
    </form>

    <!-- Color Bar -->
    <div class="absolute top-0 left-0 w-full h-2 flex">
      <div class="h-2 bg-blue-500 flex-1"></div>
      <div class="h-2 bg-red-500 flex-1"></div>
      <div class="h-2 bg-yellow-500 flex-1"></div>
      <div class="h-2 bg-blue-500 flex-1"></div>
      <div class="h-2 bg-green-500 flex-1"></div>
      <div class="h-2 bg-red-500 flex-1"></div>
    </div>
    <!-- Wine Cards -->
    <div class="mt-6 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-4 gap-y-6 xl:gap-x-4">
      <% @wines.each do |wine| %>
        <a href="<%= wine_path(wine.id) %>" class="h-full">
          <div class="relative flex flex-col rounded-xl bg-white bg-clip-border text-gray-700 shadow-md h-full">
            <div class="relative flex justify-between items-center mt-1 overflow-hidden rounded-xl bg-white bg-clip-border text-gray-700">
              <img
                src="https://res.cloudinary.com/dttd773dq/image/upload/v1697274692/ilek-assets/images/wine-bottle_uatwvb.png"
                class="object-cover h-16"
                alt=""
                />
              <span class="block font-sans text-base font-medium leading-relaxed text-blue-gray-900 antialiased mr-3">
                <%= wine.name %>
              </span>
            </div>
            <div class="p-6">
              <div class="mb-2 flex items-center justify-between">
                <p class="block font-sans text-[#a20848] font-medium leading-relaxed text-blue-gray-900 antialiased">
                  <%= number_to_currency(wine.price, :unit => '€', :delimiter => ' ', format: '%n %u', strip_insignificant_zeros: true) %>
                </p>
              </div>
              <p class="block font-sans text-sm font-normal leading-normal text-gray-700 antialiased opacity-75">
                <%= wine.properties %>
              </p>
            </div>
            <div class="mt-auto flex justify-between p-6 pt-0">
              <div class="flex items-center">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="yellow">
                  <path d="M10 1l2.93 6.4 6.93.7-5 4.85 1.47 7.1-6.4-3.35-6.4 3.35 1.47-7.1-5-4.85 6.93-.7z"/>
                </svg>
                <p class="text-sm text-gray-500 ml-2">
                  <%= number_with_precision(wine.note, precision: 1, separator: ',') %> / 5
                </p>
              </div>
              <% if expert_signed_in? %>
                <button
                  class="middle none center rounded-lg bg-pink-500 p-3 font-sans text-xs font-bold uppercase text-white shadow-md shadow-pink-500/20 transition-all hover:shadow-lg hover:shadow-pink-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none"
                  data-ripple-light="true"
                >
                  Review this wine
                </button>
              <% end %>
            </div>
          </div>
        </a>
      <% end %>
    </div>
    <div class="flex items-center justify-center mt-6">
      <% if @pagy.pages > 1 %>
        <%= pagy_nav(@pagy, link_extra: 'class="border rounded-md px-3 py-1 text-blue-500 mx-1"', link_inactive_extra: 'class="border rounded-md px-3 py-1 text-gray-500 mx-1"').html_safe %>
      <% end %>
    </div>
  </div>
</div>

app/views/wines/show.html.erb
<div class="container mx-auto p-6">
  <div class="relative p-6 flex w-full flex-row text-gray-700">
    <div class="relative m-0 flex justify-center items-center shrink-0 overflow-hidden rounded-xl rounded-r-none bg-white bg-clip-border text-gray-700">
      <img
        src="https://res.cloudinary.com/dttd773dq/image/upload/v1697274692/ilek-assets/images/wine-bottle_uatwvb.png"
        alt="image"
        class="h-48 w-48 object-cover"
        />
    </div>
    <div class="flex items-center">
      <div>
        <h4 class="text-3xl font-bold mb-4 uppercase leading-relaxed tracking-normal text-[#a20848] antialiased">
          <%= @wine.name %>
        </h4>
        <p class="mb-8 block font-sans text-gray-500 font-normal leading-relaxed antialiased">
          <%= @wine.properties %>
        </p>
      </div>
    </div>
  </div>

  <% if expert_signed_in? %>
    <div class="flex justify-end max-w-3xl mb-6">
      <a
        href="<%= wine_show_review_path(@wine) %>"
        class="text-right inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
      >
        Review this wine
      </a>
    </div>
  <% end %>

  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-4 gap-y-6">
    <% @paginated_reviews.each do |review| %>
      <div class="bg-white max-w-sm rounded-2xl flex justify-between flex-col px-10 py-2 shadow-lg hover:shadow-2xl transition duration-500">
        <div class="mt-4 text-md text-gray-600">
          <p><%= review.message %></p>
        </div>
        <div class="mt-auto flex justify-between space-x-4 py-6">
          <div class="text-sm font-semibold">
            <%= review.expert.name %>
            <p class="font-normal text-gray-500"> <%= time_ago_in_words(review.updated_at) %></p>
          </div>
          <div class="flex">
            <% review.rating.times do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-yellow-400" viewBox="0 0 20 20" fill="currentColor">
                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"/>
              </svg>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="flex items-center justify-center mt-6">
    <% if @pagy.pages > 1 %>
      <%= pagy_nav(@pagy, link_extra: 'class="border rounded-md px-3 py-1 text-blue-500 mx-1"', link_inactive_extra: 'class="border rounded-md px-3 py-1 text-gray-500 mx-1"').html_safe %>
    <% end %>
  </div>

  <div class="h-full w-full mt-6">
    <%= react_component("PricesEvolution") %>
  </div>
</div>